[package]
name = "isolate"
version = "0.0.0"
edition = "2021"

[dependencies]
nix = { version = "0.29.0", features = ["fs", "user"] }
thiserror = "2.0.11"

[dev-dependencies]
assert_matches = "1.5.0"
