name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  RUSTFLAGS: --deny warnings

jobs:
  check-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download actionlint
        id: actionlint
        run:
          bash <(curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow
        run: ${{ steps.actionlint.outputs.executable }} -color

  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain components
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Info
        run: |
          rustup --version
          cargo --version
          cargo clippy --version

  lint:
    needs: setup

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clippy
        run: cargo clippy --all-targets --all-features

      - name: Format
        run: cargo fmt --all -- --check

      - name: Forbid
        run: |
          sudo apt-get install ripgrep
          ./bin/forbid

  build:
    needs: setup

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test

  lock:
    needs: setup

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lockfile
        run: cargo update --locked --package isolate
